/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "secondary-container": "#feb300",
        "tertiary-container": "#2c3039",
        "on-secondary-container": "#6a4800",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "on-surface-variant": "#454652",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed-dim": "#c4c6d2",
        "on-tertiary-container": "#9597a2",
        "tertiary-fixed": "#e0e2ee",
        "on-primary-fixed": "#000767",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c6c5d4",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#434750",
        "on-surface": "#191c1d",
        "primary-fixed": "#e0e0ff",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed": "#281900",
        "on-error-container": "#93000a",
        "outline": "#767683",
        "on-primary-fixed-variant": "#343d96",
        "error-container": "#ffdad6",
        "inverse-primary": "#bdc2ff",
        "secondary": "#7e5700",
        "on-secondary-fixed-variant": "#604100",
        "inverse-surface": "#2e3132",
        "surface-tint": "#4c56af",
        "secondary-fixed": "#ffdeac",
        "primary-fixed-dim": "#bdc2ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#181b24",
        "surface-container": "#edeeef",
        "surface-variant": "#e1e3e4",
        "tertiary": "#181b23",
        "primary-container": "#1a237e",
        "secondary-fixed-dim": "#ffba38",
        "on-primary-container": "#8690ee",
        "primary": "#000666",
        "accent": "#feb300"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "container-padding-desktop": "80px",
        "container-padding-mobile": "20px",
        "base": "8px",
        "section-gap": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "display-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
